# Generated by Django 4.2.11 on 2024-03-15 17:23

import cloudinary.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import djrichtextfield.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('description', models.CharField(max_length=600)),
                ('materials', djrichtextfield.models.RichTextField(max_length=10000)),
                ('steps', djrichtextfield.models.RichTextField(max_length=10000)),
                ('image', cloudinary.models.CloudinaryField(default='placeholder', max_length=255, verbose_name='image')),
                ('published_on', models.DateTimeField(auto_now_add=True)),
                ('category', models.CharField(choices=[('art', 'Art'), ('decorative', 'Decorative'), ('diy_gifts', 'DIY Gifts'), ('fashion', 'Fashion'), ('garden', 'Garden'), ('jewellery', 'Jewellery'), ('kids', 'Kids'), ('misc', 'Misc'), ('woodworking', 'Woodworking')], default='art', max_length=75)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_author', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-published_on'],
            },
        ),
    ]
