# Generated by Django 4.2.11 on 2024-03-20 21:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_project_likes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='likes',
            new_name='liked',
        ),
    ]
