# Generated by Django 4.2.11 on 2024-03-20 22:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0007_rename_liked_project_likes_delete_like'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='likes',
            field=models.ManyToManyField(blank=True, default=None, related_name='project_post', to=settings.AUTH_USER_MODEL),
        ),
    ]
